ezalgorithms/main/routes.py
from flask import render_template, request, Blueprint
from ezalgorithms.models import User, Complete
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/about')
def about():
    return render_template('about.html', title='About')

@main.route('/sorting')
def sorting():
    completed = None
    if current_user.is_authenticated:
        completed = Complete.query.filter_by(author=current_user)
        completed = [x.title for x in completed]
    return render_template('sorting.html', title='Sorting', lesson='Sorting Algorithms', completed=completed)

@main.route('/graph')
def graph():
    completed = None
    if current_user.is_authenticated:
        completed = Complete.query.filter_by(author=current_user)
        completed = [x.title for x in completed]
    return render_template('graph.html', title='Graph', lesson='Graph Algorithms', completed=completed)

@main.route('/other')
def other():
    completed = None
    if current_user.is_authenticated:
        completed = Complete.query.filter_by(author=current_user)
        completed = [x.title for x in completed]
    return render_template('other.html', title='Other', lesson='Other Algorithms', completed=completed)

ezalgorithms/other/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import current_user, login_required
from ezalgorithms import db
from ezalgorithms.models import Complete

other = Blueprint('other', __name__)

@other.route('/other/binary-search')
def binary_search():
    completed = None
    if current_user.is_authenticated:
        completed = Complete.query.filter_by(author=current_user)
        completed = [x.title for x in completed]
    return render_template('binary_search.html', title='Binary Search', topic="binary-search", completed=completed)

@other.route('/other/<string:topic>/complete', methods=['GET', 'POST'])
@login_required
def complete_topic(topic):
    complete = Complete(title=topic, author=current_user)
    db.session.add(complete)
    db.session.commit()
    flash('Congradulations, you have completed a topic!', 'success')
    return redirect(url_for('main.other'))

ezalgorithms/sorting/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import current_user, login_required
from ezalgorithms import db
from ezalgorithms.models import Complete

sorting = Blueprint('sorting', __name__)

@sorting.route('/sorting/quick-sort')
def quick_sort():
    completed = None
    if current_user.is_authenticated:
        completed = Complete.query.filter_by(author=current_user)
        completed = [x.title for x in completed]
    return render_template('quick_sort.html', title='Quick Sort', topic="quick-sort", completed=completed)

@sorting.route('/sorting/<string:topic>/complete', methods=['GET', 'POST'])
@login_required
def complete_topic(topic):
    complete = Complete(title=topic, author=current_user)
    db.session.add(complete)
    db.session.commit()
    flash('Congradulations, you have completed a topic!', 'success')
    return redirect(url_for('main.sorting'))

ezalgorithms/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ezalgorithms import db, bcrypt
from ezalgorithms.models import User
from ezalgorithms.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from ezalgorithms.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.about'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account as been created! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.about'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.about'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.about'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your accout has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.about'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.about'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

ezalgorithms/templates/binary_search.html
{% extends "topic_layout.html" %}
<!------------------------------------------------------->
{% block main_body %}
<p>
Binary search makes it quick and easy to find an element quickly in a sorted list. Unlike linear search 
which has to look at every element in a list when searching, binary search will at most look at only 
Log(N) + 1 elements. Binary search works by repeatedly dividing the search interval in half and checking 
if the key is less than or greater than the middle element in the interval. If the key is less, narrow the 
interval to the lower half. Otherwise narrow the interval to the upper half. Of course if the element is 
equal to the key then we are done. Below is the steps for Binary search:
</p>
<ol>
    <li>Compare x with the middle element</li>
    <li>If x matches the middle element, we return the mid index</li>
    <li>Else if x is greater than the middle element, repeat for the right half of the list</li>
    <li>Else if x is less than the middle element, repeat for the left half of the list</li>
</ol>
<br><br>
To visualize binary search, notice in the below diagram that at each step the list is divided in two:
</p>
<div class="spacer10"></div>
<img src="{{ url_for('static', filename='assets/binary_search.png') }}" class="topic-img">
<div class="spacer10"></div>
<p>
<br><br>
Below is the iterative implementation of Binary Search written in python:
<div class="content-section">
    <code>
        <pre>
# l: list to be searched
# low: lower bound of the list
# high: upper bound of the list
# x: key 
def binarySearch(l, low, high, x):

    while low <= high: 
    
        mid = low + (high - low) // 2; 
            
        # Check if x is present at mid 
        if l[mid] == x: 
            return mid 
    
        # If x is greater, ignore left half 
        elif l[mid] < x: 
            low = mid + 1
    
        # If x is smaller, ignore right half 
        else: 
            high = mid - 1
        
    # If we reach here, then the element 
    # was not present 
    return -1
        </pre>
    </code>
<div class="spacer10"></div>
</div>
</p>
{% endblock main_body %}
<!------------------------------------------------------->
{% block problem %}
<h2>Where is the Marble?</h2>
<p>
Raju and Meena love to play with Marbles. They have got a lot of marbles with numbers written on them. 
At the beginning, Raju would place the marbles one after another in ascending order of the numbers 
written on them. Then Meena would ask Raju to find the first marble with a certain number. She would 
count 1...2...3. Raju gets one point for correct answer, and Meena gets the point if Raju fails. After 
some fixed number of trials the game ends and the player with maximum points wins. Today it’s your chance 
to play as Raju. Being the smart kid, you’d be taking the favor of a computer. But don’t underestimate 
Meena, she had written a program to keep track how much time you’re taking to give all the answers. So now 
you have to write a program, which will help you in your role as Raju.
<br>
<h2>Input</h2>
There can be multiple test cases. Total no of test cases is less than 65. Each test case consists begins 
with 2 integers: N the number of marbles and Q the number of queries Mina would make. The next N lines 
would contain the numbers written on the N marbles. These marble numbers will not come in any particular 
order. Following Q lines will have Q queries. Be assured, none of the input numbers are greater than 10000 
and none of them are negative. Input is terminated by a test case where N = 0 and Q = 0.
<br><br>
<h2>Output</h2>
For each test case output the serial number of the case. For each of the queries, print one line of output. 
The format of this line will depend upon whether or not the query number is written upon any of the marbles. 
The two different formats are described below:
<ul>
    <li>‘x found at y’, if the first marble with number x was found at position y. Positions are numbered 1,2,...,N.</li>
    <li>‘x not found’, if the marble with number x is not present.</li>
</ul>
<br><br>
</p>
{% endblock problem %}
<!------------------------------------------------------->
{% block input %}
<p>
4 1<br>2<br>3<br>5<br>1<br>5<br>5 2<br>1<br>3<br>3<br>3<br>1<br>2<br>3<br>0 0
</p>
{% endblock input %}
<!------------------------------------------------------->
{% block output %}
CASE# 1:<br>5 found at 4<br>CASE# 2:<br>2 not found<br>3 found at 3
{% endblock output %}
<!------------------------------------------------------->
{% block completed %}
    <a href="{{ url_for('other.complete_topic', topic=topic) }}" class='btn btn-dark mt-1 mb-1'>Mark As Completed</a>
{% endblock completed %}
<!------------------------------------------------------->
{% block solution %}
<code>
    <pre>
import sys

def binarySearch(l, low, high, x):

    while low <= high: 
    
        mid = low + (high - low) // 2; 
            
        if l[mid] == x: 
            return mid 
    
        elif l[mid] < x: 
            low = mid + 1
    
        else: 
            high = mid - 1

    return -1

lines = sys.stdin.readlines()
case = 0
i = 0

while lines[i].strip() != '0 0':
    case+=1
    sys.stdout.write(f"CASE# {case}:\n")
    line = lines[i].split()
    n = int(line[0])
    q = int(line[1])

    marbles = list(map(int, lines[i+1:i+n+1]))
    queries = list(map(int, lines[i+n+1:i+n+q+1]))

    i = i + n + q + 1

    marbles.sort()

    for j in queries:
        high = len(marbles) - 1
        ans = -1
        while True:
            index = binarySearch(marbles, 0, high, j)
            if index != -1:
                ans = index
                high = index - 1
            elif index == -1:
                if ans == -1: 
                    sys.stdout.write(f"{j} not found\n")
                    break
                else:
                    sys.stdout.write(f"{j} found at {ans+1}\n")
                    break
    </pre>
</code>
{% endblock solution %}

ezalgorithms/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <script src="https://kit.fontawesome.com/5d07bb4bd6.js" crossorigin="anonymous"></script>

    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>EZ Algorithms</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">EZ Algorithms</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link {% if title == 'About' %}active{% endif %}" href="{{ url_for('main.about') }}">About</a>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle {% if (title != 'About') and (title != 'Account') and (title != 'Login') and (title != 'Register') %}active{% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Lessons
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('main.sorting') }}">Sorting Algorithms</a>
                                <a class="dropdown-item" href="{{ url_for('main.graph') }}">Graph Algorithms</a>
                                <a class="dropdown-item" href="{{ url_for('main.other') }}">Other Algorithms</a>
                        </li>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link {% if title == 'Account' %}active{% endif %}" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link {% if title == 'Register' %}active{% endif %}" href="{{ url_for('users.register') }}">Register</a>
                            <a class="nav-item nav-link {% if title == 'Login' %}active{% endif %}" href="{{ url_for('users.login') }}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </main>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>About</h6>
                    <p class="text-justify">
EZ Algorithms is a free online source to teach algorithms in the simplest way possible. Our goal is provide 
only the information necessary to to get started using an algorithm in as little time as possible.
                    </p>
                </div>
    
                <div class="col-xs-6 col-md-3">
                    <h6>Lessons</h6>
                    <ul class="footer-links">
                        <li><a href="{{ url_for('main.sorting') }}">Sorting Algorithms</a></li>
                        <li><a href="{{ url_for('main.graph') }}">Graph Algorithms</a></li>
                        <li><a href="{{ url_for('main.other') }}">Other</a></li>
                    </ul>
                </div>
    
                <div class="col-xs-6 col-md-3">
                    <h6>Quick Links</h6>
                    <ul class="footer-links">
                        <li><a href="{{ url_for('main.about') }}">About Us</a></li>
                        <li><a href="#">Contact Us</a></li>
                        {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('users.account') }}">Account</a></li>
                            <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        {% else %}
                            <li><a href="{{ url_for('users.register') }}">Register</a></li>
                            <li><a href="{{ url_for('users.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved</p>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="social-icons">
                        <li><a class="github" target="_blank" rel="noopener noreferrer" href="https://github.com/AustinBush32/EZ-Algorithms"><i class="fab fa-github"></i></a></li>
                        <li><a class="linkedin" target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/austin-bush-46914a16a/"><i class="fab fa-linkedin"></i></a></li>   
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Site footer -->
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

ezalgorithms/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }} 
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }} 
                    {% endif %}

                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-dark")}}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request')}}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Accout? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now </a>
        </small>
    </div>
{% endblock content %}

ezalgorithms/templates/other.html
{% extends "lesson_layout.html" %}

{% block zero_zero %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/brute_force.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Brute Force</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock zero_zero %}

<!------------------------------------------------------------------------------------------------->

{% block zero_one %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/greedy.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Greedy Algorithm</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock zero_one %}

<!------------------------------------------------------------------------------------------------->

{% block zero_two %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/dp.png') }}" class="article-img">
        <h2><a class="article-title" href="#">Dynamic Programming</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock zero_two %}

<!------------------------------------------------------------------------------------------------->

{% block one_zero %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        {% if completed and "binary-search" in completed %}
        <i class="far fa-check-square"></i>
        {% endif %}
        <img src="{{ url_for('static', filename='assets/binary_search.gif') }}" class="article-img">
        <h2><a class="article-title" href="{{ url_for('other.binary_search') }}">Binary Search</a></h2>
        <p>
Binary search is an optimal searching algorithm for sorted arrays.
        </p>
    </div>
</article>
{% endblock one_zero %}

<!------------------------------------------------------------------------------------------------->

{% block one_one %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/linear_search.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Linear Search</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock one_one %}

ezalgorithms/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }} 
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-dark")}}
            </div>
        </form>
    </div>
{% endblock content %}

ezalgorithms/templates/sorting.html
{% extends "lesson_layout.html" %}

{% block zero_zero %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        {% if completed and "quick-sort" in completed %}
            <i class="far fa-check-square"></i>
        {% endif %}
        <img src="{{ url_for('static', filename='assets/quick_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="{{ url_for('sorting.quick_sort') }}">Quicksort</a></h2>
        <p>
Quicksort is a comparison sort based on the divide-and-conquer strategy that is asymptotically optinal
 for comparison sorting.<br><br>
        </p>
    </div>
</article>
{% endblock zero_zero %}

<!------------------------------------------------------------------------------------------------->

{% block zero_one %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        
        <img src="{{ url_for('static', filename='assets/bubble_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Bubble Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock zero_one %}

<!------------------------------------------------------------------------------------------------->

{% block zero_two %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/heapsort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Heap Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock zero_two %}

<!------------------------------------------------------------------------------------------------->

{% block one_zero %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/insertion_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Insertion Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock one_zero %}

<!------------------------------------------------------------------------------------------------->

{% block one_one %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/merge_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Merge Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock one_one %}

<!------------------------------------------------------------------------------------------------->

{% block one_two %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/selection_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Selection Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock one_two %}

<!------------------------------------------------------------------------------------------------->

{% block two_zero %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/radix_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Radix Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock two_zero %}

<!------------------------------------------------------------------------------------------------->

{% block two_one %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/shell_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Shell Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock two_one %}

<!------------------------------------------------------------------------------------------------->

{% block two_two %}
<article class="media content-section-size-adjusted">
    <div class="media-body">
        <img src="{{ url_for('static', filename='assets/counting_sort.gif') }}" class="article-img">
        <h2><a class="article-title" href="#">Counting Sort</a></h2>
        <p>
Comming Soon.
        </p>
    </div>
</article>
{% endblock two_two %}

<!------------------------------------------------------------------------------------------------->